const ADD_JOB = 'ADD_JOB';
const GET_JOB_LIST = 'GET_JOB_LIST';

const ADD_JOB_TYPE = 'ADD_JOB_TYPE';
const GET_JOB_TYPE_LIST = 'GET_JOB_TYPE_LIST';

const GET_LANE_LIST = 'GET_LANE_LIST';
const ADD_LANE = 'ADD_LANE';